services:
  mongo:
    container_name: db
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:  # Adicione um healthcheck
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')", "--username", "root", "--password", "root", "--authenticationDatabase", "admin"]
      interval: 5s
      timeout: 30s
      retries: 5

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db  # Use o container_name (db) ou o nome do serviço (mongo)
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: admin  # Opcional: proteção básica para o mongo-express
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      mongo:
        condition: service_healthy  # Só inicia após o MongoDB estar pronto

  redis:
    container_name: redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

volumes:
  mongo-data: